version: "3.7"

services:
  backend:
    container_name: blog-backend
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    restart: always
    command: docker/django/start.sh
    env_file:
      - docker/django/.env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  rq:
    container_name: blog-rq
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: python manage.py rqworker default
    env_file:
      - docker/django/.env
    depends_on:
      - db
      - redis

  redis:
    container_name: blog-redis
    image: redis:5.0.4-alpine
    restart: on-failure
    ports:
      - "6379"

  nginx:
    container_name: blog-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80

  db:
    container_name: blog-db
    image: postgres:12-alpine
    restart: always
    env_file:
      - docker/postgres/.env
    volumes:
      - pgdata_blog:${PGDATA:-/var/lib/postgresql/data}
    ports:
      - 5432

volumes:
    pgdata_blog:
