# Generated by Django 2.2.1 on 2019-06-26 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='blog url')),
                ('description', models.TextField(verbose_name='description')),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='subscriptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('publication', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.Blog', verbose_name='blog')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='UsersReaderThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='users_read',
            field=models.ManyToManyField(blank=True, related_name='user_read', through='blog.UsersReaderThrough', to=settings.AUTH_USER_MODEL, verbose_name='Users have read'),
        ),
    ]
