FROM python:3.7.3-stretch

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY Pipfile Pipfile.lock ./
RUN pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --dev --system

COPY ./docker/django/start-dev.sh ./start-dev.sh
RUN chmod +x start-dev.sh

COPY . .

EXPOSE 8000
